# Form implementation generated from reading ui file 'class_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_class_page(object):    
    def __init__(self, static):
        super().__init__()
        self.static = static
        self.data = {}

    def screen_size(self, teacher_main_page):
        screen_geometry = QtWidgets.QApplication.primaryScreen().availableGeometry()
        width = screen_geometry.width()
        height = screen_geometry.height()
        if width >= self.static["window-size"]["width"] and height >= self.static["window-size"]["height"]:
            teacher_main_page.setMinimumSize(QtCore.QSize(self.static["window-size"]["width"], self.static["window-size"]["height"]))
            qr=teacher_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            teacher_main_page.move(qr.topLeft())
        else:
            teacher_main_page.setMinimumSize(QtCore.QSize(width, height))
            qr=teacher_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            teacher_main_page.move(qr.topLeft())
        
    def refresh(self, class_page):
        self.class_page_vertical_layout.setSpacing(self.static["layout-spacing"])

        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])
        self.menu_horizontal_layout.setSpacing(self.static["menu"]["layout"]["spacing"])

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)

        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["subtitle"])
        self.class_label.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.topic_course_enable_btn.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.course_label.setFont(font)

        self.course_label.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]-10))

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.courses_combo_box.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.topic_label.setFont(font)

        self.topic_label.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]-10))

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.topic_combo_box.setFont(font)

        self.topic_combo_box.setMinimumHeight(self.static["topic"]["height"]-10)
        self.courses_combo_box.setMinimumHeight(self.static["topic"]["height"]-10)

        courses_combo_size = self.courses_combo_box.sizeHint()
        self.courses_combo_box.setMinimumWidth(courses_combo_size.width())
        
        self.topics_result(class_page)        

    def topics(self):
        self.topic_combo_box.clear()
        self.topic_combo_box.addItem("")
        self.topic_combo_box.setItemText(0, "")
        index = 1
        combobox_index = self.courses_combo_box.currentIndex()        
        if combobox_index < 1:
            self.topic_course_enable_btn.setEnabled(False)
            self.topic_combo_box.setMaximumWidth(self.static["topic"]["small-width"])
            return
        self.topic_course_enable_btn.setEnabled(True)
        for subject in self.data[combobox_index-1][self.courses_combo_box.currentText()]:
            self.topic_combo_box.addItem("")
            self.topic_combo_box.setItemText(index, subject["topic_name"])
            index+=1
        topic_combo_size = self.topic_combo_box.sizeHint()
        self.topic_combo_box.setMinimumWidth(topic_combo_size.width())
        

    def courses(self):
        self.courses_combo_box.clear()
        self.courses_combo_box.addItem("")
        self.courses_combo_box.setItemText(0, "")
        index = 1
        combobox_index = 1
        for course in self.data:
            for name, lines in course.items():
                if index % 2==0:
                    self.courses_combo_box.addItem("")
                    self.courses_combo_box.setItemText(combobox_index, name)
                    combobox_index+=1
                index+=1

    def topics_result(self, class_page):
        if self.data == {}:
            return

        self.student_list_scroll_area_vertical_layout.removeWidget(self.student_list_group_box)

        self.student_list_group_box = QtWidgets.QGroupBox(parent=self.student_list_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.student_list_group_box.setSizePolicy(sizePolicy)
        self.student_list_group_box.setTitle("")
        self.student_list_group_box.setObjectName("student_list_group_box")

        self.student_list_grid_layout = QtWidgets.QGridLayout(self.student_list_group_box)
        self.student_list_grid_layout.setContentsMargins(self.static["menu"]["layout"]["left"], 0, self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])
        self.student_list_grid_layout.setSpacing(5)
        self.student_list_grid_layout.setObjectName("student_list_grid_layout")

        if self.courses_combo_box.currentIndex() < 1 or self.topic_combo_box.currentIndex() < 1:
            self.student_list_scroll_area_vertical_layout.addWidget(self.student_list_group_box)
            QtCore.QMetaObject.connectSlotsByName(class_page)
            return

        self.test_result_label = QtWidgets.QLabel("Teszt eredmény", parent=self.student_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.test_result_label.sizePolicy().hasHeightForWidth())
        self.test_result_label.setSizePolicy(sizePolicy)
        self.test_result_label.setMinimumSize(QtCore.QSize(75, 30))
        self.test_result_label.setMaximumSize(QtCore.QSize(171, 30))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.test_result_label.setFont(font)
        self.test_result_label.setObjectName("test_result_label")
        #self.test_result_form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.test_result_label)
        self.student_list_grid_layout.addWidget(self.test_result_label, 0, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignCenter)

        index = 1
        #for
        for line in self.data[self.courses_combo_box.currentIndex()-1][self.courses_combo_box.currentText()][self.topic_combo_box.currentIndex()-1]["students"]:
            student_name = QtWidgets.QLabel(line["student_name"], parent=self.student_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHeightForWidth(student_name.sizePolicy().hasHeightForWidth())
            student_name.setSizePolicy(sizePolicy)
            student_name.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"], self.static["topic"]["height"]))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            student_name.setFont(font)
            student_name.setWordWrap(True)
            student_name.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:15px;padding-right:15px")
            student_name.setObjectName(f"student_name_{line["id"]}")
            #self.student_name_form_layout.setWidget(index, QtWidgets.QFormLayout.ItemRole.LabelRole, student_name)
            self.student_list_grid_layout.addWidget(student_name, index, 0, 1, 1)#)

            student_email = QtWidgets.QLabel(line["student_email"], parent=self.student_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
            student_email.setSizePolicy(sizePolicy)
            student_email.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"], self.static["topic"]["height"]))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"]-1)
            student_email.setFont(font)
            student_email.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:15px;padding-right:15px")
            student_email.setObjectName(f"student_email_{line["id"]}")
            #self.student_email_form_layout.setWidget(index, QtWidgets.QFormLayout.ItemRole.LabelRole, student_email)
            self.student_list_grid_layout.addWidget(student_email, index, 1, 1, 1)#, QtCore.Qt.AlignmentFlag.AlignLeft)

            student_results = QtWidgets.QPushButton("Összes eredmény", parent=self.student_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHeightForWidth(student_results.sizePolicy().hasHeightForWidth())
            student_results.setSizePolicy(sizePolicy)
            student_results.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-20, self.static["topic"]["height"]))
            student_results.setMaximumSize(QtCore.QSize(16777215, self.static["topic"]["height"]))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            student_results.setFont(font)
            student_results.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            student_results.setToolTip("")
            student_results.setAutoFillBackground(False)
            student_results.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:10px;padding-right:10px;}\n"
                                            "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:10px;padding-right:10px;}")
            student_results.setObjectName(f"student_results_{line["student_name"]}_{line["id"]}")
            self.student_list_grid_layout.addWidget(student_results, index, 2, 1, 1)
            student_results.clicked.connect(class_page.student_results)

            modul_list_item_group_box = QtWidgets.QGroupBox(parent=self.student_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
            sizePolicy.setHeightForWidth(modul_list_item_group_box.sizePolicy().hasHeightForWidth())
            modul_list_item_group_box.setSizePolicy(sizePolicy)
            modul_list_item_group_box.setMinimumSize(QtCore.QSize(0, 50))
            modul_list_item_group_box.setStyleSheet("border:none")
            modul_list_item_group_box.setTitle("")
            modul_list_item_group_box.setObjectName(f"modul_list_item_group_box_{index}")

            test_result_vertical_layout = QtWidgets.QHBoxLayout(modul_list_item_group_box)
            test_result_vertical_layout.setContentsMargins(0, 0, 0, 0)
            test_result_vertical_layout.setSpacing(5)
            test_result_vertical_layout.setObjectName(f"test_result_vertical_layout_{index}")

            finished_icon_label = QtWidgets.QLabel(parent=modul_list_item_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHeightForWidth(finished_icon_label.sizePolicy().hasHeightForWidth())
            finished_icon_label.setSizePolicy(sizePolicy)
            finished_icon_label.setMinimumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
            finished_icon_label.setMaximumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
            finished_icon_label.setStyleSheet("")
            finished_icon_label.setText("")
            finished_icon_label.setObjectName(f"finished_icon_label_{line["id"]}")
            test_result_vertical_layout.addWidget(finished_icon_label)
            finished_icon_label.setScaledContents(True)
            req = self.data[self.courses_combo_box.currentIndex()-1][self.courses_combo_box.currentText()][self.topic_combo_box.currentIndex()-1]['test_task_number']
            req = req if req!=0 else 1
            if round(line["best_correct_answers"]/req*100)>=self.data[self.courses_combo_box.currentIndex()-1][self.courses_combo_box.currentText()][self.topic_combo_box.currentIndex()-1]["test_required_percentage"]:
                finished_icon_label.setPixmap(QtGui.QPixmap("utils/images/ok-icon.png"))  
            else:
                finished_icon_label.setPixmap(QtGui.QPixmap("utils/images/not-ok-icon.png"))  

            test_result_group_box = QtWidgets.QGroupBox(parent=modul_list_item_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHeightForWidth(test_result_group_box.sizePolicy().hasHeightForWidth())
            test_result_group_box.setSizePolicy(sizePolicy)
            test_result_group_box.setMinimumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
            test_result_group_box.setMaximumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
            test_result_group_box.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10;")
            test_result_group_box.setTitle("")
            test_result_group_box.setObjectName(f"test_result_group_box_{index}")

            result_vertical_layout = QtWidgets.QVBoxLayout(test_result_group_box)
            result_vertical_layout.setContentsMargins(10, 0, 10, 0)
            result_vertical_layout.setObjectName(f"result_vertical_layout_{index}")

            task_number_label = QtWidgets.QLabel(f'{line["best_correct_answers"]}/{self.data[self.courses_combo_box.currentIndex()-1][self.courses_combo_box.currentText()][self.topic_combo_box.currentIndex()-1]["test_task_number"]}', parent=test_result_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
            sizePolicy.setHeightForWidth(task_number_label.sizePolicy().hasHeightForWidth())
            task_number_label.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"]-2)
            task_number_label.setFont(font)
            task_number_label.setStyleSheet("border:none")
            task_number_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            task_number_label.setObjectName(f"task_number_label_{line["id"]}")
            result_vertical_layout.addWidget(task_number_label)

            num = self.data[self.courses_combo_box.currentIndex()-1][self.courses_combo_box.currentText()][self.topic_combo_box.currentIndex()-1]['test_task_number']
            num = num if num!=0 else 1
            test_percent_label = QtWidgets.QLabel(f"{round(line["best_correct_answers"]/num*100)}%", parent=test_result_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
            sizePolicy.setHeightForWidth(test_percent_label.sizePolicy().hasHeightForWidth())
            test_percent_label.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"]-2)
            test_percent_label.setFont(font)
            test_percent_label.setStyleSheet("border:none")
            test_percent_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            test_percent_label.setObjectName(f"test_percent_label_{line["id"]}")
            result_vertical_layout.addWidget(test_percent_label)
            test_result_vertical_layout.addWidget(test_result_group_box)
            self.student_list_grid_layout.addWidget(modul_list_item_group_box, index, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignCenter)

            index+=1       

        self.student_list_scroll_area_vertical_layout.addWidget(self.student_list_group_box)

        QtCore.QMetaObject.connectSlotsByName(class_page)        

    def setupUi(self, class_page):
        class_page.setObjectName("class_page")
        class_page.resize(720, 480)
        class_page.setMinimumSize(QtCore.QSize(720, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        class_page.setPalette(palette)
        self.class_page_vertical_layout = QtWidgets.QVBoxLayout(class_page)
        self.class_page_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.class_page_vertical_layout.setSpacing(self.static["layout-spacing"])
        self.class_page_vertical_layout.setObjectName("class_page_vertical_layout")
        self.menu_group_box = QtWidgets.QGroupBox(parent=class_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        
        
        sizePolicy.setHeightForWidth(self.menu_group_box.sizePolicy().hasHeightForWidth())
        self.menu_group_box.setSizePolicy(sizePolicy)
        self.menu_group_box.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.menu_group_box.setPalette(palette)
        self.menu_group_box.setAutoFillBackground(True)
        self.menu_group_box.setStyleSheet("")
        self.menu_group_box.setTitle("")
        self.menu_group_box.setObjectName("menu_group_box")

        self.menu_horizontal_layout = QtWidgets.QHBoxLayout(self.menu_group_box)
        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])
        self.menu_horizontal_layout.setSpacing(self.static["menu"]["layout"]["spacing"])
        self.menu_horizontal_layout.setObjectName("menu_horizontal_layout")

        self.menu_label = QtWidgets.QLabel(parent=self.menu_group_box)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)
        self.menu_label.setObjectName("menu_label")
        self.menu_horizontal_layout.addWidget(self.menu_label)

        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.menu_horizontal_layout.addItem(spacerItem)

        self.font_size_combo_box = QtWidgets.QComboBox(parent=self.menu_group_box)
        self.font_size_combo_box.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)
        self.font_size_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.font_size_combo_box.setStyleSheet("")
        self.font_size_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.font_size_combo_box.setObjectName("font_size_combo_box")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.menu_horizontal_layout.addWidget(self.font_size_combo_box)

        self.back_to_main_page_cmd_link_btn = QtWidgets.QCommandLinkButton(parent=self.menu_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        
        
        sizePolicy.setHeightForWidth(self.back_to_main_page_cmd_link_btn.sizePolicy().hasHeightForWidth())
        self.back_to_main_page_cmd_link_btn.setSizePolicy(sizePolicy)
        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)
        self.back_to_main_page_cmd_link_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_to_main_page_cmd_link_btn.setObjectName("back_to_main_page_cmd_link_btn")
        icon = QtGui.QIcon('utils/images/left-arrow.png')           
        self.back_to_main_page_cmd_link_btn.setIcon(icon)
        self.menu_horizontal_layout.addWidget(self.back_to_main_page_cmd_link_btn)
        self.class_page_vertical_layout.addWidget(self.menu_group_box)

        self.title_group_box = QtWidgets.QGroupBox(parent=class_page)
        self.title_group_box.setStyleSheet("border:none")
        self.title_group_box.setTitle("")
        self.title_group_box.setObjectName("title_group_box")
        self.title_group_box_1_horizontal_layout = QtWidgets.QHBoxLayout(self.title_group_box)
        self.title_group_box_1_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.title_group_box_1_horizontal_layout.setSpacing(5)
        self.title_group_box_1_horizontal_layout.setObjectName("title_group_box_1_horizontal_layout")

        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_group_box_1_horizontal_layout.addItem(spacerItem1)

        self.class_label = QtWidgets.QLabel(parent=self.title_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        
        
        sizePolicy.setHeightForWidth(self.class_label.sizePolicy().hasHeightForWidth())
        self.class_label.setSizePolicy(sizePolicy)
        self.class_label.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["subtitle"])
        self.class_label.setFont(font)
        self.class_label.setObjectName("class_label")
        self.title_group_box_1_horizontal_layout.addWidget(self.class_label)
        

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_group_box_1_horizontal_layout.addItem(spacerItem2)

        self.topic_course_enable_btn = QtWidgets.QPushButton(parent=self.title_group_box)
        self.topic_course_enable_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.topic_course_enable_btn.setFont(font)
        self.topic_course_enable_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.topic_course_enable_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;}\n"
                                        "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;}")
        self.topic_course_enable_btn.setEnabled(False)
        self.topic_course_enable_btn.setObjectName("topic_course_enable_btn")
        self.title_group_box_1_horizontal_layout.addWidget(self.topic_course_enable_btn)

        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_group_box_1_horizontal_layout.addItem(spacerItem3)
        self.class_page_vertical_layout.addWidget(self.title_group_box)

        self.title_group_box_2 = QtWidgets.QGroupBox(parent=class_page)
        self.title_group_box_2.setStyleSheet("border:none")
        self.title_group_box_2.setTitle("")
        self.title_group_box_2.setObjectName("title_group_box_2")

        self.title_group_box_2_horizontal_layout = QtWidgets.QHBoxLayout(self.title_group_box_2)
        self.title_group_box_2_horizontal_layout.setContentsMargins(10, 0, 10, 0)
        self.title_group_box_2_horizontal_layout.setSpacing(5)
        self.title_group_box_2_horizontal_layout.setObjectName("title_group_box_2_horizontal_layout")



        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_group_box_2_horizontal_layout.addItem(spacerItem4)

        self.subtopic_list_item_group_box = QtWidgets.QGroupBox(parent=self.title_group_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        
        
        sizePolicy.setHeightForWidth(self.subtopic_list_item_group_box.sizePolicy().hasHeightForWidth())
        self.subtopic_list_item_group_box.setSizePolicy(sizePolicy)
        self.subtopic_list_item_group_box.setTitle("")
        self.subtopic_list_item_group_box.setObjectName("subtopic_list_item_group_box")

        self.subtopic_list_item_grid_layout = QtWidgets.QGridLayout(self.subtopic_list_item_group_box)
        self.subtopic_list_item_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.subtopic_list_item_grid_layout.setHorizontalSpacing(5)
        self.subtopic_list_item_grid_layout.setVerticalSpacing(5)
        self.subtopic_list_item_grid_layout.setObjectName("subtopic_list_item_grid_layout")

        self.course_label = QtWidgets.QLabel(parent=self.subtopic_list_item_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        
        
        sizePolicy.setHeightForWidth(self.course_label.sizePolicy().hasHeightForWidth())
        self.course_label.setSizePolicy(sizePolicy)
        self.course_label.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.course_label.setFont(font)
        self.course_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:15px;padding-right:15px")
        self.course_label.setObjectName("course_label")
        #self.title_group_box_2_horizontal_layout.addWidget(self.course_label)
        self.subtopic_list_item_grid_layout.addWidget(self.course_label, 0, 0)

        self.courses_combo_box = QtWidgets.QComboBox(parent=self.subtopic_list_item_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        
        
        sizePolicy.setHeightForWidth(self.courses_combo_box.sizePolicy().hasHeightForWidth())
        self.courses_combo_box.setSizePolicy(sizePolicy)
        self.courses_combo_box.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"], self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.courses_combo_box.setFont(font)
        self.courses_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.courses_combo_box.setStyleSheet("QComboBox {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;}\n"
                                        "QComboBox:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;}\n"
                                        "QAbstractItemView{selection-color: black; selection-background-color: #55aa00; background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;padding-top:5px; padding-bottom:5px;}")
        self.courses_combo_box.setCurrentText("")
        self.courses_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.courses_combo_box.setObjectName("courses_combo_box")
        self.courses_combo_box.addItem("")
        self.courses_combo_box.setItemText(0, "")
        #self.title_group_box_2_horizontal_layout.addWidget(self.courses_combo_box)
        self.subtopic_list_item_grid_layout.addWidget(self.courses_combo_box, 0, 1)

        self.topic_label = QtWidgets.QLabel(parent=self.subtopic_list_item_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        
        
        sizePolicy.setHeightForWidth(self.topic_label.sizePolicy().hasHeightForWidth())
        self.topic_label.setSizePolicy(sizePolicy)
        self.topic_label.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.topic_label.setFont(font)
        self.topic_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:15px;padding-right:15px")
        self.topic_label.setObjectName("topic_label")
        #self.title_group_box_2_horizontal_layout.addWidget(self.topic_label)
        self.subtopic_list_item_grid_layout.addWidget(self.topic_label, 1, 0)
        
        self.topic_combo_box = QtWidgets.QComboBox(parent=self.subtopic_list_item_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        
        
        sizePolicy.setHeightForWidth(self.topic_combo_box.sizePolicy().hasHeightForWidth())
        self.topic_combo_box.setSizePolicy(sizePolicy)
        self.topic_combo_box.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"], self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.topic_combo_box.setFont(font)
        self.topic_combo_box.setStyleSheet("QComboBox {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;}\n"
                                        "QComboBox:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;}\n"
                                        "QAbstractItemView{selection-color: black; selection-background-color: #55aa00; background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:15px;padding-right:15px;padding-top:5px; padding-bottom:5px;}")
        self.topic_combo_box.setCurrentText("")
        self.topic_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.topic_combo_box.setObjectName("topic_combo_box")
        self.topic_combo_box.addItem("")
        self.topic_combo_box.setItemText(0, "")
        #self.title_group_box_2_horizontal_layout.addWidget(self.topic_combo_box)
        self.subtopic_list_item_grid_layout.addWidget(self.topic_combo_box, 1, 1)

        self.title_group_box_2_horizontal_layout.addWidget(self.subtopic_list_item_group_box)

        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_group_box_2_horizontal_layout.addItem(spacerItem6)

        self.class_page_vertical_layout.addWidget(self.title_group_box_2)

        self.line = QtWidgets.QFrame(parent=class_page)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        self.line.setPalette(palette)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.class_page_vertical_layout.addWidget(self.line)
        self.student_list_scroll_area = QtWidgets.QScrollArea(parent=class_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        
        
        sizePolicy.setHeightForWidth(self.student_list_scroll_area.sizePolicy().hasHeightForWidth())
        self.student_list_scroll_area.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.student_list_scroll_area.setPalette(palette)
        self.student_list_scroll_area.setStyleSheet("border:none; background-color:#83cbeb")
        self.student_list_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.student_list_scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.student_list_scroll_area.setWidgetResizable(True)
        self.student_list_scroll_area.setObjectName("student_list_scroll_area")
        self.student_list_scroll_area_contents = QtWidgets.QWidget()
        self.student_list_scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 720, 241))
        self.student_list_scroll_area_contents.setObjectName("student_list_scroll_area_contents")
        self.student_list_scroll_area_vertical_layout = QtWidgets.QVBoxLayout(self.student_list_scroll_area_contents)
        self.student_list_scroll_area_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.student_list_scroll_area_vertical_layout.setSpacing(0)
        self.student_list_scroll_area_vertical_layout.setObjectName("student_list_scroll_area_vertical_layout")
        self.student_list_scroll_area_vertical_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)


        self.student_list_group_box = QtWidgets.QGroupBox(parent=self.student_list_scroll_area_contents)
        self.student_list_group_box.setTitle("")
        self.student_list_group_box.setObjectName("student_list_group_box")

        self.student_list_grid_layout = QtWidgets.QHBoxLayout(self.student_list_group_box)
        self.student_list_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.student_list_grid_layout.setSpacing(5)
        self.student_list_grid_layout.setObjectName("student_list_grid_layout")

        self.student_list_scroll_area_vertical_layout.addWidget(self.student_list_group_box)

        self.student_list_scroll_area.setWidget(self.student_list_scroll_area_contents)

        self.class_page_vertical_layout.addWidget(self.student_list_scroll_area)

        self.retranslateUi(class_page)

        match class_page.user_settings['font-size']:
            case 'small':
                self.font_size_combo_box.setCurrentIndex(0)
            case 'medium':
                self.font_size_combo_box.setCurrentIndex(1)
            case 'big':
                self.font_size_combo_box.setCurrentIndex(2)

        QtCore.QMetaObject.connectSlotsByName(class_page)

    def retranslateUi(self, class_page):
        _translate = QtCore.QCoreApplication.translate
        class_page.setWindowTitle(_translate("class_page", "SmartStudy"))
        class_page.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))
        self.menu_label.setText(_translate("class_page", "Osztályok"))
        self.font_size_combo_box.setItemText(0, _translate("class_page", "Kis betűméret"))
        self.font_size_combo_box.setItemText(1, _translate("class_page", "Közepes betűméret"))
        self.font_size_combo_box.setItemText(2, _translate("class_page", "Nagy betűméret"))
        self.back_to_main_page_cmd_link_btn.setText(_translate("class_page", "Vissza a kezdőlapra"))
        self.class_label.setText(_translate("class_page", class_page.class_name))
        self.topic_course_enable_btn.setText(_translate("class_page", "Témakörök engedélyezése és tesztek szintjeinek beállítása"))
        self.course_label.setText(_translate("class_page", "Kurzus kiválasztása:"))
        self.topic_label.setText(_translate("class_page", "Témakör kiválasztása:"))