# Form implementation generated from reading ui file 'class_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import re
from PyQt6 import QtCore, QtGui, QtWidgets
from utils.validators import NAME_VALIDATOR, EMAIL_VALIDATOR, CLASSNAME_VALIDATOR

class Ui_class_page(object):    
    def __init__(self, static):
        super().__init__()
        self.static = static
        self.student_data = []
        self.class_data = []

    def screen_size(self, teacher_main_page):
        screen_geometry = QtWidgets.QApplication.primaryScreen().availableGeometry()
        width = screen_geometry.width()
        height = screen_geometry.height()
        if width >= self.static["window-size"]["width"] and height >= self.static["window-size"]["height"]:
            teacher_main_page.setMinimumSize(QtCore.QSize(self.static["window-size"]["width"], self.static["window-size"]["height"]))
            qr=teacher_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            teacher_main_page.move(qr.topLeft())
        else:
            teacher_main_page.setMinimumSize(QtCore.QSize(width, height))
            qr=teacher_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            teacher_main_page.move(qr.topLeft())
        
    def refresh(self, class_page):
        self.verticalLayout.setSpacing(self.static["layout-spacing"])

        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)

        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.class_name_line_edit.setFont(font)
        self.class_name_line_edit.setMinimumHeight(self.static["topic"]["height"]-10)
        self.class_name_line_edit.setMaximumWidth(self.static["topic"]["small-width"]-60)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.new_student_btn.setFont(font)
        self.new_student_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]))

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.student_action_btn.setFont(font)
        self.student_action_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]))

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.student_action_label.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.student_action_combo_box.setFont(font)
        self.student_action_combo_box.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]-10))

        self.new_student_grid_layout.setSpacing(self.static["menu"]["layout"]["spacing"])

        self.class_edit_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], 0, self.static["menu"]["layout"]["right"], 0)
        self.class_edit_horizontal_layout.setSpacing(self.static["subtitle-spacing"])

        self.save_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_btn.setFont(font)

        self.courses_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.courses_btn.setFont(font)

        self.edit_transmission_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.edit_transmission_btn.setFont(font)

        self.delete_class_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.delete_class_btn.setFont(font)

        self.student_list(class_page)
        
    def student_list(self, class_page):

        self.student_scroll_area_vertical_layout.removeWidget(self.student_list_group_box)#remove
        
        self.student_list_group_box = QtWidgets.QGroupBox(parent=self.student_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.student_list_group_box.sizePolicy().hasHeightForWidth())
        self.student_list_group_box.setSizePolicy(sizePolicy)
        self.student_list_group_box.setTitle("")
        self.student_list_group_box.setObjectName("student_list_group_box")
        
        self.student_list_horizontal_layout = QtWidgets.QHBoxLayout(self.student_list_group_box)
        self.student_list_horizontal_layout.setContentsMargins(0, 10, 0, self.static["menu"]["layout"]["bottom"])
        self.student_list_horizontal_layout.setSpacing(5)
        self.student_list_horizontal_layout.setObjectName("student_list_horizontal_layout")
        
        spacerItem15 = QtWidgets.QSpacerItem(171, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.student_list_horizontal_layout.addItem(spacerItem15)
        
        self.student_select_group_box = QtWidgets.QGroupBox(parent=self.student_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.student_select_group_box.sizePolicy().hasHeightForWidth())
        self.student_select_group_box.setSizePolicy(sizePolicy)
        self.student_select_group_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.student_select_group_box.setTitle("")
        self.student_select_group_box.setObjectName("student_select_group_box")
        
        self.student_select_form_layout = QtWidgets.QFormLayout(self.student_select_group_box)
        self.student_select_form_layout.setContentsMargins(0, 0, 0, 0)
        self.student_select_form_layout.setHorizontalSpacing(0)
        self.student_select_form_layout.setVerticalSpacing(5)
        self.student_select_form_layout.setObjectName("student_select_form_layout")

        self.student_name_group_box = QtWidgets.QGroupBox(parent=self.student_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.student_name_group_box.sizePolicy().hasHeightForWidth())
        self.student_name_group_box.setSizePolicy(sizePolicy)
        self.student_name_group_box.setTitle("")
        self.student_name_group_box.setObjectName("student_name_group_box")
        
        self.student_name_form_layout = QtWidgets.QFormLayout(self.student_name_group_box)
        self.student_name_form_layout.setContentsMargins(0, self.static["topic"]["height"]+5, 0, 0)
        self.student_name_form_layout.setHorizontalSpacing(0)
        self.student_name_form_layout.setVerticalSpacing(5)
        self.student_name_form_layout.setObjectName("student_name_form_layout")

        self.student_email_group_box = QtWidgets.QGroupBox(parent=self.student_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.student_email_group_box.sizePolicy().hasHeightForWidth())
        self.student_email_group_box.setSizePolicy(sizePolicy)
        self.student_email_group_box.setTitle("")
        self.student_email_group_box.setObjectName("student_email_group_box")
        
        self.student_email_form_layout = QtWidgets.QFormLayout(self.student_email_group_box)
        self.student_email_form_layout.setContentsMargins(0, self.static["topic"]["height"]+5, 0, 0)
        self.student_email_form_layout.setHorizontalSpacing(0)
        self.student_email_form_layout.setVerticalSpacing(5)
        self.student_email_form_layout.setObjectName("student_email_form_layout")

        self.student_edit_group_box = QtWidgets.QGroupBox(parent=self.student_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.student_edit_group_box.sizePolicy().hasHeightForWidth())
        self.student_edit_group_box.setSizePolicy(sizePolicy)
        self.student_edit_group_box.setTitle("")
        self.student_edit_group_box.setObjectName("student_edit_group_box")
        
        self.student_edit_form_layout = QtWidgets.QFormLayout(self.student_edit_group_box)
        self.student_edit_form_layout.setContentsMargins(0, self.static["topic"]["height"]+5, 0, 0)
        self.student_edit_form_layout.setHorizontalSpacing(0)
        self.student_edit_form_layout.setVerticalSpacing(5)
        self.student_edit_form_layout.setObjectName("student_edit_form_layout")

        self.student_select_btn = QtWidgets.QPushButton(parent=self.student_select_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHeightForWidth(self.student_select_btn.sizePolicy().hasHeightForWidth())
        self.student_select_btn.setSizePolicy(sizePolicy)
        self.student_select_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
        self.student_select_btn.setMaximumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
        self.student_select_btn.setText("")
        self.student_select_btn.setIcon(QtGui.QIcon("utils/images/not-ok-icon.png"))
        self.student_select_btn.setStyleSheet(f"background-color:white; border: 2px solid black;")
        self.student_select_btn.setIconSize(QtCore.QSize(self.static["topic"]["height"],self.static["topic"]["height"]))
        self.student_select_btn.setObjectName(f"student_select_btn")
        self.student_select_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.student_select_form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.student_select_btn)
        self.student_select_btn.clicked.connect(class_page.student_select_all)        

        if self.student_data == []:
            self.student_select_btn.setHidden(True)
        else:
            self.student_select_btn.setHidden(False)

        index = 1
        for line in self.student_data:
            student_select_btn = QtWidgets.QPushButton(parent=self.student_select_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(student_select_btn.sizePolicy().hasHeightForWidth())
            student_select_btn.setSizePolicy(sizePolicy)
            student_select_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
            student_select_btn.setMaximumSize(QtCore.QSize(self.static["topic"]["height"], self.static["topic"]["height"]))
            student_select_btn.setText("")
            student_select_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            student_select_btn.setIcon(QtGui.QIcon("utils/images/not-ok-icon.png"))
            student_select_btn.setStyleSheet(f"background-color:white; border: 2px solid black;")
            student_select_btn.setIconSize(QtCore.QSize(self.static["topic"]["height"],self.static["topic"]["height"]))
            student_select_btn.setObjectName(f"student_select_btn_{index}_{line['id']}")
            self.student_select_form_layout.setWidget(index, QtWidgets.QFormLayout.ItemRole.LabelRole, student_select_btn)
            student_select_btn.clicked.connect(class_page.student_select)

            student_name_label = QtWidgets.QLabel(line["student_name"], parent=self.student_name_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(student_name_label.sizePolicy().hasHeightForWidth())
            student_name_label.setSizePolicy(sizePolicy)
            student_name_label.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]))
            student_name_label.setMaximumSize(QtCore.QSize(16777215, self.static["topic"]["height"]))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            student_name_label.setFont(font)
            student_name_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
            student_name_label.setObjectName(f"student_name_label_{line['id']}")
            self.student_name_form_layout.setWidget(index, QtWidgets.QFormLayout.ItemRole.LabelRole, student_name_label)

            student_email_label = QtWidgets.QLabel(line["email"], parent=self.student_email_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(student_email_label.sizePolicy().hasHeightForWidth())
            student_email_label.setSizePolicy(sizePolicy)
            student_email_label.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]))
            student_email_label.setMaximumSize(QtCore.QSize(16777215, self.static["topic"]["height"]))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            student_email_label.setFont(font)
            student_email_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
            student_email_label.setObjectName(f"student_email_label_{line['id']}")
            self.student_email_form_layout.setWidget(index, QtWidgets.QFormLayout.ItemRole.LabelRole, student_email_label)

            student_edit_btn = QtWidgets.QPushButton("Szerkesztés", parent=self.student_edit_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(student_edit_btn.sizePolicy().hasHeightForWidth())
            student_edit_btn.setSizePolicy(sizePolicy)
            student_edit_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"]-60, self.static["topic"]["height"]))
            student_edit_btn.setMaximumSize(QtCore.QSize(16777215, self.static["topic"]["height"]))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            student_edit_btn.setFont(font)
            student_edit_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:10px;padding-right:10px;}\n"
                                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:10px;padding-right:10px;}")
            student_edit_btn.setObjectName(f"student_edit_btn_{line["student_name"]}_{line['id']}")
            student_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            self.student_edit_form_layout.setWidget(index, QtWidgets.QFormLayout.ItemRole.LabelRole, student_edit_btn)
            student_edit_btn.clicked.connect(class_page.student_edit)

            index+=1
        
        self.student_list_horizontal_layout.addWidget(self.student_select_group_box)

        self.student_list_horizontal_layout.addWidget(self.student_name_group_box)

        self.student_list_horizontal_layout.addWidget(self.student_email_group_box)

        self.student_list_horizontal_layout.addWidget(self.student_edit_group_box)
        
        spacerItem16 = QtWidgets.QSpacerItem(171, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.student_list_horizontal_layout.addItem(spacerItem16)
        
        self.student_scroll_area_vertical_layout.addWidget(self.student_list_group_box)

    def setupUi(self, class_page):
        class_page.setObjectName("class_page")
        class_page.resize(720, 480)
        class_page.setMinimumSize(QtCore.QSize(720, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        class_page.setPalette(palette)

        self.verticalLayout = QtWidgets.QVBoxLayout(class_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(self.static["layout-spacing"])
        self.verticalLayout.setObjectName("verticalLayout")

        self.menu_group_box = QtWidgets.QGroupBox(parent=class_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.menu_group_box.sizePolicy().hasHeightForWidth())
        self.menu_group_box.setSizePolicy(sizePolicy)
        self.menu_group_box.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.menu_group_box.setPalette(palette)
        self.menu_group_box.setAutoFillBackground(True)
        self.menu_group_box.setStyleSheet("")
        self.menu_group_box.setTitle("")
        self.menu_group_box.setObjectName("menu_group_box")

        self.menu_horizontal_layout = QtWidgets.QHBoxLayout(self.menu_group_box)
        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])
        self.menu_horizontal_layout.setObjectName("menu_horizontal_layout")

        self.menu_label = QtWidgets.QLabel(parent=self.menu_group_box)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)
        self.menu_label.setObjectName("menu_label")
        self.menu_horizontal_layout.addWidget(self.menu_label)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.menu_horizontal_layout.addItem(spacerItem)

        self.font_size_combo_box = QtWidgets.QComboBox(parent=self.menu_group_box)
        self.font_size_combo_box.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)
        self.font_size_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.font_size_combo_box.setStyleSheet("")
        self.font_size_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.font_size_combo_box.setObjectName("font_size_combo_box")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.menu_horizontal_layout.addWidget(self.font_size_combo_box)

        self.back_to_main_page_cmd_link_btn = QtWidgets.QCommandLinkButton(parent=self.menu_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.back_to_main_page_cmd_link_btn.sizePolicy().hasHeightForWidth())
        self.back_to_main_page_cmd_link_btn.setSizePolicy(sizePolicy)
        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)
        self.back_to_main_page_cmd_link_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_to_main_page_cmd_link_btn.setObjectName("back_to_main_page_cmd_link_btn")
        icon = QtGui.QIcon('utils/images/left-arrow.png')           
        self.back_to_main_page_cmd_link_btn.setIcon(icon)
        self.menu_horizontal_layout.addWidget(self.back_to_main_page_cmd_link_btn)
        self.verticalLayout.addWidget(self.menu_group_box)

        self.class_edit_group_box = QtWidgets.QGroupBox(parent=class_page)
        self.class_edit_group_box.setObjectName("class_edit_group_box")
        self.class_edit_group_box.setStyleSheet("border:none;")

        self.class_edit_horizontal_layout = QtWidgets.QHBoxLayout(self.class_edit_group_box)
        self.class_edit_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], 0, self.static["menu"]["layout"]["right"], 0)
        self.class_edit_horizontal_layout.setSpacing(self.static["subtitle-spacing"])
        self.class_edit_horizontal_layout.setObjectName("class_edit_horizontal_layout")

        self.class_name_line_edit = QtWidgets.QLineEdit(parent=self.class_edit_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.class_name_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.class_name_line_edit.setFont(font)
        self.class_name_line_edit.setMinimumHeight(self.static["topic"]["height"]-10)
        self.class_name_line_edit.setMaximumWidth(self.static["topic"]["small-width"]-60)
        self.class_name_line_edit.setObjectName("class_name_line_edit")
        self.class_name_line_edit.setValidator(CLASSNAME_VALIDATOR)
        self.class_name_line_edit.setMaxLength(20)
        self.class_edit_horizontal_layout.addWidget(self.class_name_line_edit)
        self.class_name_line_edit.setPlaceholderText("Név")

        self.save_btn = QtWidgets.QPushButton(parent=self.class_edit_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_btn.setFont(font)
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.save_btn.setObjectName("save_btn")
        self.class_edit_horizontal_layout.addWidget(self.save_btn)
        if class_page.class_name=="":
            self.save_btn.setEnabled(False)

        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.class_edit_horizontal_layout.addItem(spacerItem1)

        self.courses_btn = QtWidgets.QPushButton(parent=self.class_edit_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.courses_btn.setSizePolicy(sizePolicy)
        self.courses_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.courses_btn.setFont(font)
        self.courses_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.courses_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.courses_btn.setObjectName("courses_btn")        
        self.class_edit_horizontal_layout.addWidget(self.courses_btn)
        if class_page.class_id ==-1:
            self.courses_btn.setEnabled(False)

        spacerItem0 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.class_edit_horizontal_layout.addItem(spacerItem0)

        self.edit_transmission_btn = QtWidgets.QPushButton(parent=self.class_edit_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.edit_transmission_btn.setSizePolicy(sizePolicy)
        self.edit_transmission_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.edit_transmission_btn.setFont(font)
        self.edit_transmission_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_transmission_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.edit_transmission_btn.setObjectName("edit_transmission_btn")
        self.class_edit_horizontal_layout.addWidget(self.edit_transmission_btn)
        if class_page.class_id ==-1:
            self.edit_transmission_btn.setEnabled(False)

        self.delete_class_btn = QtWidgets.QPushButton(parent=self.class_edit_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.delete_class_btn.setSizePolicy(sizePolicy)
        self.delete_class_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.delete_class_btn.setFont(font)
        self.delete_class_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_class_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.delete_class_btn.setObjectName("delete_class_btn")
        self.class_edit_horizontal_layout.addWidget(self.delete_class_btn)
        if class_page.class_id ==-1:
            self.delete_class_btn.setEnabled(False)

        self.student_scroll_area = QtWidgets.QScrollArea(parent=class_page)
        self.student_scroll_area.setStyleSheet("border:none; background-color:#83cbeb")
        self.student_scroll_area.setWidgetResizable(True)
        self.student_scroll_area.setObjectName("student_scroll_area")

        self.student_scroll_area_contents = QtWidgets.QWidget()
        self.student_scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 720, 295))
        self.student_scroll_area_contents.setObjectName("student_scroll_area_contents")

        self.student_scroll_area_vertical_layout = QtWidgets.QVBoxLayout(self.student_scroll_area_contents)
        self.student_scroll_area_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.student_scroll_area_vertical_layout.setSpacing(0)
        self.student_scroll_area_vertical_layout.setObjectName("student_scroll_area_vertical_layout")

        self.new_student_group_box = QtWidgets.QGroupBox(parent=self.student_scroll_area_contents)
        self.new_student_group_box.setTitle("")
        self.new_student_group_box.setObjectName("new_student_group_box")
        
        self.new_student_grid_layout = QtWidgets.QGridLayout(self.new_student_group_box)
        self.new_student_grid_layout.setContentsMargins(0, 10, 0, 10)
        self.new_student_grid_layout.setSpacing(5)
        self.new_student_grid_layout.setObjectName("new_student_grid_layout")

        spacerItem11 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.new_student_grid_layout.addItem(spacerItem11, 0, 0, 3, 1)

        self.new_student_btn = QtWidgets.QPushButton(parent=self.new_student_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.new_student_btn.setSizePolicy(sizePolicy)
        self.new_student_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.new_student_btn.setFont(font)
        self.new_student_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.new_student_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                            "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.new_student_btn.setObjectName("new_student_btn_-1")
        self.new_student_grid_layout.addWidget(self.new_student_btn, 0, 1, 3, 1)
        if class_page.class_id ==-1:
            self.new_student_btn.setEnabled(False)

        self.student_action_label = QtWidgets.QLabel(parent=self.new_student_group_box)
        self.student_action_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.student_action_label.setFont(font)
        self.student_action_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.student_action_label.setObjectName("student_action_label")
        self.new_student_grid_layout.addWidget(self.student_action_label, 0, 2, 1, 1)

        self.student_action_combo_box = QtWidgets.QComboBox(parent=self.new_student_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_action_combo_box.setSizePolicy(sizePolicy)
        self.student_action_combo_box.setMinimumSize(QtCore.QSize(self.static["topic"]["title-width"], self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.student_action_combo_box.setFont(font)
        self.student_action_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.student_action_combo_box.setStyleSheet("QComboBox {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:10px;padding-right:10px;}\n"
        "QComboBox:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:10px;padding-right:10px;}\n"
        "QAbstractItemView{selection-color: black; selection-background-color: #55aa00; background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:10px;padding-right:10px;padding-top:5px; padding-bottom:5px;}")
        self.student_action_combo_box.setObjectName("student_action_combo_box")
        self.student_action_combo_box.addItem("")
        self.student_action_combo_box.setItemText(0, "")
        self.student_action_combo_box.addItem("")
        self.student_action_combo_box.addItem("")
        self.student_action_combo_box.addItem("")
        self.new_student_grid_layout.addWidget(self.student_action_combo_box, 2, 2, 1, 1)
        if class_page.class_id == -1:
            self.student_action_combo_box.setEnabled(False)

        self.student_action_btn = QtWidgets.QPushButton(parent=self.new_student_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.student_action_btn.setSizePolicy(sizePolicy)
        self.student_action_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.student_action_btn.setFont(font)
        self.student_action_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.student_action_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.student_action_btn.setObjectName("student_action_btn")
        self.student_action_btn.setEnabled(False)
        self.new_student_grid_layout.addWidget(self.student_action_btn, 0, 3, 3, 1)

        spacerItem12 = QtWidgets.QSpacerItem(0, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.new_student_grid_layout.addItem(spacerItem12, 0, 4, 3, 1)

        self.student_scroll_area_vertical_layout.addWidget(self.new_student_group_box)
        
        self.student_line = QtWidgets.QFrame(parent=self.student_scroll_area_contents)
        self.student_line.setMinimumSize(QtCore.QSize(0, 0))
        self.student_line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.student_line.setStyleSheet("background-color:white;")
        self.student_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.student_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.student_line.setObjectName("student_line")
        self.student_scroll_area_vertical_layout.addWidget(self.student_line)
        
        self.student_list_group_box = QtWidgets.QGroupBox(parent=self.student_scroll_area_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.student_list_group_box.sizePolicy().hasHeightForWidth())
        self.student_list_group_box.setSizePolicy(sizePolicy)
        self.student_list_group_box.setTitle("")
        self.student_list_group_box.setObjectName("student_list_group_box")
        
        self.student_list_horizontal_layout = QtWidgets.QHBoxLayout(self.student_list_group_box)
        self.student_list_horizontal_layout.setContentsMargins(0, 10, 0, 0)
        self.student_list_horizontal_layout.setSpacing(5)
        self.student_list_horizontal_layout.setObjectName("student_list_horizontal_layout")
        
        self.student_scroll_area_vertical_layout.addWidget(self.student_list_group_box)
        
        self.student_scroll_area.setWidget(self.student_scroll_area_contents)        

        self.verticalLayout.addWidget(self.class_edit_group_box)
        self.verticalLayout.addWidget(self.student_scroll_area)

        self.retranslateUi(class_page)

        match class_page.user_settings['font-size']:
            case 'small':
                self.font_size_combo_box.setCurrentIndex(0)
            case 'medium':
                self.font_size_combo_box.setCurrentIndex(1)
            case 'big':
                self.font_size_combo_box.setCurrentIndex(2)

        QtCore.QMetaObject.connectSlotsByName(class_page)

    def retranslateUi(self, class_page):
        _translate = QtCore.QCoreApplication.translate
        class_page.setWindowTitle(_translate("class_page", "SmartStudy"))
        class_page.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))
        self.menu_label.setText(_translate("class_page", "Osztály szerkesztése/Új"))
        self.font_size_combo_box.setItemText(0, _translate("class_page", "Kis betűméret"))
        self.font_size_combo_box.setItemText(1, _translate("class_page", "Közepes betűméret"))
        self.font_size_combo_box.setItemText(2, _translate("class_page", "Nagy betűméret"))
        self.back_to_main_page_cmd_link_btn.setText(_translate("class_page", "Vissza a kezdőlapra"))
        self.class_name_line_edit.setText(_translate("class_page", class_page.class_name))
        self.edit_transmission_btn.setText(_translate("class_page", "Osztály kezelés leadása"))
        self.delete_class_btn.setText(_translate("class_page", "Osztály törlése"))
        self.courses_btn.setText(_translate("class_page", "Kurzusok"))
        self.save_btn.setText(_translate("class_page", "Mentés"))
        self.new_student_btn.setText(_translate("class_page", "Új tanuló"))
        self.student_action_btn.setText(_translate("class_page", "Mehet!"))
        self.student_action_label.setText(_translate("class_page", "Művelek a kijelöltekkel:"))
        self.student_action_combo_box.setItemText(1, _translate("class_page", "Hozzáadás osztályhoz"))
        self.student_action_combo_box.setItemText(2, _translate("class_page", "Leadás kezelésből"))
        self.student_action_combo_box.setItemText(3, _translate("class_page", "Archiválás"))

class ClassDialog(QtWidgets.QDialog):
    def __init__(self, class_data, text_size, button_size, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Osztály választás")
        self.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))
        self.class_data = class_data

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.setPalette(palette)
        
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setContentsMargins(30, 30, 30, 30)
        self.layout.setSpacing(15)
        self.layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.class_combo_box = QtWidgets.QComboBox()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.class_combo_box.setSizePolicy(sizePolicy)
        self.class_combo_box.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.class_combo_box.setFont(font)
        self.class_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.class_combo_box.setStyleSheet("QComboBox {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                            "QComboBox:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                            "QAbstractItemView{selection-color: black; selection-background-color: #55aa00; background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;padding-top:5px; padding-bottom:5px;}")
        self.class_combo_box.currentIndexChanged.connect(self.save_class_enable)

        self.ok_button = QtWidgets.QPushButton("Mentés")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.ok_button.setSizePolicy(sizePolicy)
        self.ok_button.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.ok_button.setFont(font)
        self.ok_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ok_button.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.ok_button.setEnabled(False)
        
        self.cancel_button = QtWidgets.QPushButton("Mégse")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.cancel_button.setFont(font)
        self.cancel_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_button.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.layout.addWidget(self.class_combo_box)
        self.layout.addWidget(self.ok_button)
        self.layout.addWidget(self.cancel_button)
        
        self.ok_button.clicked.connect(self.accept)
        self.cancel_button.clicked.connect(self.reject)
        
        for item in self.class_data:
            if item['secretary_name']!='':
                self.class_combo_box.addItem(item["class_name"], item["id"])
        self.setLayout(self.layout)

    def save_class_enable(self):
        if self.class_combo_box.currentText()=="":
            self.ok_button.setEnabled(False)
        else:
            self.ok_button.setEnabled(True)
    
    def get_selected_id(self):
        if self.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            selected_index = self.class_combo_box.currentIndex()
            return self.class_combo_box.itemData(selected_index)
        else:
            return -1

class StudentDialog(QtWidgets.QDialog):
    def __init__(self, text_size, button_size, name="", email="", parent=None):
        super().__init__(parent)
        self.setWindowTitle("Tanuló szerkesztése/új")
        self.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.setPalette(palette)

        self.layout = QtWidgets.QGridLayout()
        self.layout.setContentsMargins(30, 30, 30, 30)
        self.layout.setSpacing(15)
        self.layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.student_name_label = QtWidgets.QLabel("Név:")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_name_label.setSizePolicy(sizePolicy)
        self.student_name_label.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.student_name_label.setFont(font)
        self.student_name_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
        self.student_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.layout.addWidget(self.student_name_label, 0, 0, 1, 1)

        self.student_name_line_edit = QtWidgets.QLineEdit(name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_name_line_edit.setSizePolicy(sizePolicy)
        self.student_name_line_edit.setStyleSheet(f"background-color:white; border: 2px solid black;")
        self.student_name_line_edit.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.student_name_line_edit.setFont(font)
        self.student_name_line_edit.setValidator(NAME_VALIDATOR)
        self.student_name_line_edit.setMaxLength(255)
        self.student_name_line_edit.setPlaceholderText("Név")
        self.layout.addWidget(self.student_name_line_edit, 0, 1, 1, 2)
        self.student_name_line_edit.textChanged.connect(self.save_name_enable)

        self.student_email_label = QtWidgets.QLabel("E-mail:")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_email_label.setSizePolicy(sizePolicy)
        self.student_email_label.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.student_email_label.setFont(font)
        self.student_email_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
        self.student_email_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.layout.addWidget(self.student_email_label, 1, 0, 1, 1)

        if email=="":
            self.student_email_label_edit = QtWidgets.QLineEdit(email)
            self.student_email_label_edit.setStyleSheet(f"background-color:white; border: 2px solid black;")
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
            self.student_email_label_edit.setValidator(EMAIL_VALIDATOR)
            self.student_email_label_edit.setMaxLength(255)
            self.student_email_label_edit.setPlaceholderText("E-mail")
            self.student_email_label_edit.textChanged.connect(self.save_name_enable)
        else:
            self.student_email_label_edit = QtWidgets.QLabel(email)
            self.student_email_label_edit.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_email_label_edit.setMinimumSize(button_size)        
        self.student_email_label_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.student_email_label_edit.setFont(font)
        self.layout.addWidget(self.student_email_label_edit, 1, 1, 1, 2)

        self.student_cancel_btn = QtWidgets.QPushButton("Mégse")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_cancel_btn.setSizePolicy(sizePolicy)
        self.student_cancel_btn.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.student_cancel_btn.setFont(font)
        self.student_cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.student_cancel_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.layout.addWidget(self.student_cancel_btn, 2, 0, 1, 1)
        self.student_cancel_btn.clicked.connect(self.reject)

        self.student_save_btn = QtWidgets.QPushButton("Mentés")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_save_btn.setSizePolicy(sizePolicy)
        self.student_save_btn.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.student_save_btn.setFont(font)
        self.student_save_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.student_save_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.layout.addWidget(self.student_save_btn, 2, 1, 1, 1)
        self.student_save_btn.clicked.connect(self.accept)
        if name =="":
            self.student_save_btn.setEnabled(False)

        self.student_save_and_new_btn = QtWidgets.QPushButton("Mentés és új")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.student_save_and_new_btn.setSizePolicy(sizePolicy)
        self.student_save_and_new_btn.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.student_save_and_new_btn.setFont(font)
        self.student_save_and_new_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.student_save_and_new_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.layout.addWidget(self.student_save_and_new_btn, 2, 2, 1, 1)
        self.student_save_and_new_btn.clicked.connect(self.save_and_new)
        if name =="":
            self.student_save_and_new_btn.setEnabled(False)

        self.new = False

        if email!="":
            self.student_save_and_new_btn.setHidden(True)

        self.setLayout(self.layout)
    
    def save_name_enable(self):
        if not re.match(r'\b[\w.]+@[\w.]+\.\w{2,}\b', self.student_email_label_edit.text()):
            return
        if self.student_name_line_edit.text()=="" or self.student_email_label_edit.text()=="" or self.student_name_line_edit.text().endswith(' ') :
            self.student_save_btn.setEnabled(False)
            self.student_save_and_new_btn.setEnabled(False)
        else:
            self.student_save_btn.setEnabled(True)
            self.student_save_and_new_btn.setEnabled(True)

    def save_and_new(self):
        self.new = True
        self.accept()

    def get_selected_id(self):
        if self.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            name = self.student_name_line_edit.text()
            email = self.student_email_label_edit.text()
            return name, email, self.new
        else:
            return "", "", False


class DeleteDialog(QtWidgets.QDialog):
    def __init__(self, text_size, button_size, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Törlés")
        self.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.setPalette(palette)

        self.layout = QtWidgets.QGridLayout()
        self.layout.setContentsMargins(30, 30, 30, 30)
        self.layout.setSpacing(15)
        self.layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.warning_sign_label = QtWidgets.QLabel("Biztosan szeretné folytatni? A tanulók elveszthetik az előrehaladásukat!")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        self.warning_sign_label.setSizePolicy(sizePolicy)
        self.warning_sign_label.setMinimumSize(button_size)
        self.warning_sign_label.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.warning_sign_label.setFont(font)
        self.warning_sign_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
        self.warning_sign_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.layout.addWidget(self.warning_sign_label, 0, 0, 1, 2)

        self.decline_btn = QtWidgets.QPushButton("Mégse")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.decline_btn.setSizePolicy(sizePolicy)
        self.decline_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.decline_btn.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.decline_btn.setFont(font)
        self.layout.addWidget(self.decline_btn, 1, 0, 1, 1)
        self.decline_btn.clicked.connect(self.reject)

        self.delete_btn = QtWidgets.QPushButton("Törlés")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.delete_btn.setSizePolicy(sizePolicy)
        self.delete_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.delete_btn.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.delete_btn.setFont(font)
        self.layout.addWidget(self.delete_btn, 1, 1, 1, 1)
        self.delete_btn.clicked.connect(self.accept)

        self.setLayout(self.layout)

    def accept_delete(self):
        if self.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            return True
        else:
            return False