# Form implementation generated from reading ui file 'course_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from utils.validators import COURSE_NAME_VALIDATOR

class Ui_course_page(object):
    def __init__(self, static):
        super().__init__()
        self.static = static
        self.course_data = []
        self.subject_data = []
        self.teacher_data = []

    def screen_size(self, course_main_page):
        screen_geometry = QtWidgets.QApplication.primaryScreen().availableGeometry()
        width = screen_geometry.width()
        height = screen_geometry.height()
        if width >= self.static["window-size"]["width"] and height >= self.static["window-size"]["height"]:
            course_main_page.setMinimumSize(QtCore.QSize(self.static["window-size"]["width"], self.static["window-size"]["height"]))
            qr=course_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            course_main_page.move(qr.topLeft())
        else:
            course_main_page.setMinimumSize(QtCore.QSize(width, height))
            qr=course_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            course_main_page.move(qr.topLeft())

    def course_list(self, course_page):
        self.course_vertical_layout.setSpacing(self.static["layout-spacing"])

        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], 0)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)

        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], 0)
        self.save_horizontal_layout.setSpacing(self.static["subtitle-spacing"])

        self.class_name_label.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.class_name_label.setFont(font)

        self.scroll_area_vertical_layout.removeWidget(self.course_list_group_box)

        self.course_list_group_box = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.course_list_group_box.setSizePolicy(sizePolicy)
        
        self.course_list_group_box.setTitle("")
        self.course_list_group_box.setObjectName("course_list_group_box")

        self.course_list_grid_layout = QtWidgets.QGridLayout(self.course_list_group_box)
        self.course_list_grid_layout.setContentsMargins(10, 10, 10, 10)
        self.course_list_grid_layout.setVerticalSpacing(5)
        self.course_list_grid_layout.setHorizontalSpacing(5)
        self.course_list_grid_layout.setObjectName("course_list_grid_layout")
        self.course_list_grid_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.scroll_area_vertical_layout.addWidget(self.course_list_group_box)

        course_name_label = QtWidgets.QLabel("Kurzus neve:", parent=self.course_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        course_name_label.setSizePolicy(sizePolicy)
        course_name_label.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        course_name_label.setFont(font)
        course_name_label.setObjectName("course_name_label")
        course_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.course_list_grid_layout.addWidget(course_name_label, 0, 0, 1, 1)

        subject_name_label = QtWidgets.QLabel("Tárgy neve:", parent=self.course_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        subject_name_label.setSizePolicy(sizePolicy)
        subject_name_label.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        subject_name_label.setFont(font)
        subject_name_label.setObjectName("subject_name_label")
        subject_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.course_list_grid_layout.addWidget(subject_name_label, 0, 1, 1, 1)

        index1 = 1
        for course in self.course_data:
            course_name_line_edit = QtWidgets.QLineEdit(course["course_name"], parent=self.course_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
            course_name_line_edit.setSizePolicy(sizePolicy)
            course_name_line_edit.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            course_name_line_edit.setFont(font)
            course_name_line_edit.setStyleSheet("background-color: white; border: 2px solid black;")
            course_name_line_edit.setObjectName(f"course_name_line_edit_{index1}")
            course_name_line_edit.setValidator(COURSE_NAME_VALIDATOR)
            course_name_line_edit.setMaxLength(20)
            course_name_line_edit.textChanged.connect(course_page.save_enable)
            self.course_list_grid_layout.addWidget(course_name_line_edit, index1, 0, 1, 1)

            subject_label = QtWidgets.QLabel(course["subject"], parent=self.course_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
            subject_label.setSizePolicy(sizePolicy)
            subject_label.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            subject_label.setFont(font)
            subject_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
            subject_label.setObjectName(f"subject_label_{course["subject"]}")
            self.course_list_grid_layout.addWidget(subject_label, index1, 1, 1, 1)

            save_btn = QtWidgets.QPushButton("Mentés", parent=self.course_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
            save_btn.setSizePolicy(sizePolicy)
            save_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            save_btn.setFont(font)
            save_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            save_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
            save_btn.setObjectName(f"save_btn_{index1}_{course['id']}")
            self.course_list_grid_layout.addWidget(save_btn, index1, 2, 1, 1)
            save_btn.setEnabled(False)
            save_btn.clicked.connect(course_page.save_course)

            delete_course_btn = QtWidgets.QPushButton("Eltávolítás", parent=self.course_list_group_box)
            delete_course_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]-10))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            delete_course_btn.setFont(font)
            delete_course_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            delete_course_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
            delete_course_btn.setObjectName(f"delete_course_btn_{course['id']}")
            self.course_list_grid_layout.addWidget(delete_course_btn, index1, 3, 1, 1)
            delete_course_btn.clicked.connect(course_page.delete_course)

            index1+=1

            for teacher in course["teachers"]:
                teacher_name_label = QtWidgets.QLabel(teacher["teacher_name"], parent=self.course_list_group_box)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
                teacher_name_label.setSizePolicy(sizePolicy)
                teacher_name_label.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
                font = QtGui.QFont()
                font.setPointSize(self.static["font-sizes"]["text"])
                teacher_name_label.setFont(font)
                teacher_name_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
                teacher_name_label.setObjectName(f"teacher_name_label_{index1}")
                self.course_list_grid_layout.addWidget(teacher_name_label, index1, 1, 1, 1)

                remove_teacher_btn = QtWidgets.QPushButton("Eltávolítás", parent=self.course_list_group_box)
                remove_teacher_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]-10))
                font = QtGui.QFont()
                font.setPointSize(self.static["font-sizes"]["text"])
                remove_teacher_btn.setFont(font)
                remove_teacher_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                remove_teacher_btn.setObjectName(f"remove_teacher_btn_{course['id']}_{teacher['teacher_id']}")
                remove_teacher_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
                remove_teacher_btn.clicked.connect(course_page.remove_teacher)
                self.course_list_grid_layout.addWidget(remove_teacher_btn, index1, 2, 1, 1)

                index1+=1
            
            teacher_combo_box = QtWidgets.QComboBox(parent=self.course_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
            teacher_combo_box.setSizePolicy(sizePolicy)
            teacher_combo_box.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"], self.static["topic"]["height"]-10))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            teacher_combo_box.setFont(font)
            teacher_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            teacher_combo_box.setStyleSheet("QComboBox {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                            "QComboBox:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                            "QAbstractItemView{selection-color: black; selection-background-color: #55aa00; background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;padding-top:5px; padding-bottom:5px;}")
            teacher_combo_box.addItem("")
            teacher_combo_box.setItemText(0, "")
            teacher_combo_box.setObjectName(f"teacher_combo_box_{index1}")
            teacher_combo_box.currentTextChanged.connect(course_page.add_teacher_enable)
            self.course_list_grid_layout.addWidget(teacher_combo_box, index1, 1, 1, 1)

            for teacher in self.teacher_data:
                if not any(course_teacher['teacher_id'] == teacher['id'] for course_teacher in course["teachers"]) and course['subject'] in teacher['subjects']:
                    teacher_combo_box.addItem(teacher["teacher_name"], teacher["id"])

            add_teacher_btn = QtWidgets.QPushButton("Hozzáadás", parent=self.course_list_group_box)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
            add_teacher_btn.setSizePolicy(sizePolicy)
            add_teacher_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]-10))
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            add_teacher_btn.setFont(font)
            add_teacher_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            add_teacher_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                        "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
            self.course_list_grid_layout.addWidget(add_teacher_btn, index1, 2, 1, 1)
            add_teacher_btn.setObjectName(f"add_teacher_btn_{course['id']}_{index1}")
            add_teacher_btn.setEnabled(False)
            add_teacher_btn.clicked.connect(course_page.add_teacher)

            index1+=1

        course_name_line_edit = QtWidgets.QLineEdit("", parent=self.course_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        course_name_line_edit.setSizePolicy(sizePolicy)
        course_name_line_edit.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        course_name_line_edit.setFont(font)
        course_name_line_edit.setValidator(COURSE_NAME_VALIDATOR)
        course_name_line_edit.setMaxLength(20)
        course_name_line_edit.setObjectName(f"course_name_line_edit_{index1}")
        course_name_line_edit.setStyleSheet("background-color: white; border: 2px solid black;")
        self.course_list_grid_layout.addWidget(course_name_line_edit, index1, 0, 1, 1)
        course_name_line_edit.textChanged.connect(course_page.subject_enable)

        subject_combo_box = QtWidgets.QComboBox(parent=self.course_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        subject_combo_box.setSizePolicy(sizePolicy)
        subject_combo_box.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        subject_combo_box.setFont(font)
        subject_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        subject_combo_box.setStyleSheet("QComboBox {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                    "QComboBox:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                    "QAbstractItemView{selection-color: black; selection-background-color: #55aa00; background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;padding-top:5px; padding-bottom:5px;}")
        subject_combo_box.addItem("", "")
        for subject in self.subject_data:
            subject_combo_box.addItem(subject)
        subject_combo_box.setObjectName(f"subject_combo_box_{index1}")
        subject_combo_box.currentTextChanged.connect(course_page.add_course_enable)
        self.course_list_grid_layout.addWidget(subject_combo_box, index1, 1, 1, 1)
        subject_combo_box.setEnabled(False)

        new_course_btn = QtWidgets.QPushButton("Hozzáadás" ,parent=self.course_list_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        new_course_btn.setSizePolicy(sizePolicy)
        new_course_btn.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-40, self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        new_course_btn.setFont(font)
        new_course_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        new_course_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.course_list_grid_layout.addWidget(new_course_btn, index1, 2, 1, 1)
        new_course_btn.setObjectName(f"new_course_btn_{index1}")
        new_course_btn.setEnabled(False)
        new_course_btn.clicked.connect(course_page.new_course)

        self.scrollArea.setMinimumSize(QtCore.QSize(course_page.geometry().width(), course_page.geometry().height()-self.menu_group_box.height()-self.title_group_box.height()))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(course_page.geometry().width(), course_page.geometry().height()-self.menu_group_box.height()-self.title_group_box.height()))
        self.course_list_group_box.setMinimumSize(QtCore.QSize(course_page.geometry().width(), course_page.geometry().height()-self.menu_group_box.height()-self.title_group_box.height()))

    def setupUi(self, course_page):
        course_page.setObjectName("course_page")
        course_page.resize(720, 480)
        course_page.setMinimumSize(QtCore.QSize(720, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        course_page.setPalette(palette)

        self.course_vertical_layout = QtWidgets.QVBoxLayout(course_page)
        self.course_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.course_vertical_layout.setSpacing(self.static["layout-spacing"])
        self.course_vertical_layout.setObjectName("course_vertical_layout")
        self.course_vertical_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.menu_group_box = QtWidgets.QGroupBox(parent=course_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.menu_group_box.sizePolicy().hasHeightForWidth())
        self.menu_group_box.setSizePolicy(sizePolicy)
        self.menu_group_box.setMinimumHeight(self.static["topic"]["height"])

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.menu_group_box.setPalette(palette)
        self.menu_group_box.setAutoFillBackground(True)
        self.menu_group_box.setStyleSheet("")
        self.menu_group_box.setTitle("")
        self.menu_group_box.setObjectName("menu_group_box")

        self.menu_horizontal_layout = QtWidgets.QHBoxLayout(self.menu_group_box)
        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], 0)
        self.menu_horizontal_layout.setSpacing(5)
        self.menu_horizontal_layout.setObjectName("menu_horizontal_layout")

        self.menu_label = QtWidgets.QLabel(parent=self.menu_group_box)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)
        self.menu_label.setObjectName("menu_label")
        self.menu_horizontal_layout.addWidget(self.menu_label)

        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.menu_horizontal_layout.addItem(spacerItem)

        self.font_size_combo_box = QtWidgets.QComboBox(parent=self.menu_group_box)
        self.font_size_combo_box.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)
        self.font_size_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.font_size_combo_box.setStyleSheet("")
        self.font_size_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.font_size_combo_box.setObjectName("font_size_combo_box")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.menu_horizontal_layout.addWidget(self.font_size_combo_box)

        self.back_to_main_page_cmd_link_btn = QtWidgets.QCommandLinkButton(parent=self.menu_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.back_to_main_page_cmd_link_btn.sizePolicy().hasHeightForWidth())
        self.back_to_main_page_cmd_link_btn.setSizePolicy(sizePolicy)
        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)
        self.back_to_main_page_cmd_link_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_to_main_page_cmd_link_btn.setObjectName("back_to_main_page_cmd_link_btn")
        icon = QtGui.QIcon('utils/images/left-arrow.png')           
        self.back_to_main_page_cmd_link_btn.setIcon(icon)
        self.menu_horizontal_layout.addWidget(self.back_to_main_page_cmd_link_btn)
        self.course_vertical_layout.addWidget(self.menu_group_box)

        self.title_group_box = QtWidgets.QGroupBox(parent=course_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        self.title_group_box.setSizePolicy(sizePolicy)
        self.title_group_box.setStyleSheet("border:none;")
        self.title_group_box.setTitle("")
        self.title_group_box.setObjectName("title_group_box")

        self.save_horizontal_layout = QtWidgets.QHBoxLayout(self.title_group_box)
        self.save_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], 0, self.static["menu"]["layout"]["right"], 0)
        self.save_horizontal_layout.setSpacing(self.static["subtitle-spacing"])
        self.save_horizontal_layout.setObjectName("save_horizontal_layout")
        self.save_horizontal_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.class_name_label = QtWidgets.QLabel(course_page.class_name, parent=self.title_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHeightForWidth(self.class_name_label.sizePolicy().hasHeightForWidth())
        self.class_name_label.setSizePolicy(sizePolicy)
        self.class_name_label.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.class_name_label.setFont(font)
        self.class_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.class_name_label.setObjectName("course_name_label")
        self.save_horizontal_layout.addWidget(self.class_name_label)

        self.scrollArea = QtWidgets.QScrollArea(parent=course_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setStyleSheet("border:none; background-color:#83cbeb")
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)        

        self.scroll_area_vertical_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scroll_area_vertical_layout.setObjectName("scroll_area_vertical_layout")
        self.scroll_area_vertical_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.course_list_group_box = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.course_list_group_box.setTitle("")
        self.course_list_group_box.setObjectName("course_list_group_box")

        self.course_list_grid_layout = QtWidgets.QGridLayout(self.course_list_group_box)
        self.course_list_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.course_list_grid_layout.setSpacing(5)
        self.course_list_grid_layout.setObjectName("course_list_grid_layout")

        self.scroll_area_vertical_layout.addWidget(self.course_list_group_box)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.course_vertical_layout.addWidget(self.title_group_box)
        self.course_vertical_layout.addWidget(self.scrollArea)

        self.retranslateUi(course_page)

        match course_page.user_settings['font-size']:
            case 'small':
                self.font_size_combo_box.setCurrentIndex(0)
            case 'medium':
                self.font_size_combo_box.setCurrentIndex(1)
            case 'big':
                self.font_size_combo_box.setCurrentIndex(2)

        QtCore.QMetaObject.connectSlotsByName(course_page)

    def retranslateUi(self, course_page):
        _translate = QtCore.QCoreApplication.translate
        course_page.setWindowTitle(_translate("course_page", "SmartStudy"))
        course_page.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))
        self.menu_label.setText(_translate("course_page", "Kurzusok szerkesztése"))
        self.font_size_combo_box.setItemText(0, _translate("course_page", "Kis betűméret"))
        self.font_size_combo_box.setItemText(1, _translate("course_page", "Közepes betűméret"))
        self.font_size_combo_box.setItemText(2, _translate("course_page", "Nagy betűméret"))
        self.back_to_main_page_cmd_link_btn.setText(_translate("course_page", "Vissza az osztályhoz"))
        #self.new_course_btn.setText(_translate("course_page", "Új kurzus"))
        self.class_name_label.setText(_translate("course_page", course_page.class_name))


class DeleteDialog(QtWidgets.QDialog):
    def __init__(self, text_size, button_size, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Törlés")
        self.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.setPalette(palette)

        self.layout = QtWidgets.QGridLayout()
        self.layout.setContentsMargins(30, 30, 30, 30)
        self.layout.setSpacing(15)
        self.layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)


        self.warning_sign_label = QtWidgets.QLabel("Biztosan szeretné folytatni? A tanulók elveszthetik az előrehaladásukat!")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        self.warning_sign_label.setSizePolicy(sizePolicy)
        self.warning_sign_label.setMinimumSize(button_size)
        self.warning_sign_label.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.warning_sign_label.setFont(font)
        self.warning_sign_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
        self.warning_sign_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.layout.addWidget(self.warning_sign_label, 0, 0, 1, 2)

        self.decline_btn = QtWidgets.QPushButton("Mégse")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.decline_btn.setSizePolicy(sizePolicy)
        self.decline_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.decline_btn.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.decline_btn.setFont(font)
        self.layout.addWidget(self.decline_btn, 1, 0, 1, 1)
        self.decline_btn.clicked.connect(self.reject)

        self.delete_btn = QtWidgets.QPushButton("Törlés")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.delete_btn.setSizePolicy(sizePolicy)
        self.delete_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.delete_btn.setMinimumSize(button_size)
        font = QtGui.QFont()
        font.setPointSize(text_size)
        self.delete_btn.setFont(font)
        self.layout.addWidget(self.delete_btn, 1, 1, 1, 1)
        self.delete_btn.clicked.connect(self.accept)

        self.setLayout(self.layout)

    def accept_delete(self):
        if self.exec() == QtWidgets.QDialog.DialogCode.Accepted:
            return True
        else:
            return False