# Form implementation generated from reading ui file 'teacher_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from utils.validators import NAME_VALIDATOR, EMAIL_VALIDATOR

class Ui_teacher_page(object):
    def __init__(self, static):
        super().__init__()
        self.static = static
        self.teacher_subjects = []
        self.subject_data = []

    def screen_size(self, teacher_main_page):
        screen_geometry = QtWidgets.QApplication.primaryScreen().availableGeometry()
        width = screen_geometry.width()
        height = screen_geometry.height()
        if width >= self.static["window-size"]["width"] and height >= self.static["window-size"]["height"]:
            teacher_main_page.setMinimumSize(QtCore.QSize(self.static["window-size"]["width"], self.static["window-size"]["height"]))
            qr=teacher_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            teacher_main_page.move(qr.topLeft())
        else:
            teacher_main_page.setMinimumSize(QtCore.QSize(width, height))
            qr=teacher_main_page.frameGeometry()           
            cp=QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
            qr.moveCenter(cp)
            teacher_main_page.move(qr.topLeft())

    def subject_list(self, teacher_page):
        self.teacher_vertical_layout.setSpacing(self.static["layout-spacing"])

        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)

        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])
        self.save_horizontal_layout.setSpacing(self.static["subtitle-spacing"])

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_btn.setFont(font)
        self.save_btn.setMinimumHeight(self.static["topic"]["height"])

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_and_new_btn.setFont(font)
        self.save_and_new_btn.setMinimumHeight(self.static["topic"]["height"])

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.subject_combo_box.setFont(font)
        self.subject_combo_box.setMinimumHeight(self.static["topic"]["height"]-10)

        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.add_subject_btn.setFont(font)
        self.add_subject_btn.setMinimumHeight(self.static["topic"]["height"])

        self.teacher_name_line_edit.setMinimumHeight(self.static["topic"]["height"]-10)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.teacher_name_line_edit.setFont(font)

        self.teacher_email_line_edit.setMinimumHeight(self.static["topic"]["height"]-10)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.teacher_email_line_edit.setFont(font)

        self.scroll_area_vertical_layout.removeWidget(self.subject_list_group_box)        

        self.subject_list_group_box = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.subject_list_group_box.setTitle("")
        self.subject_list_group_box.setObjectName("subject_list_group_box")

        self.subject_list_grid_layout = QtWidgets.QGridLayout(self.subject_list_group_box)
        self.subject_list_grid_layout.setContentsMargins(10, 10, 10, 10)
        self.subject_list_grid_layout.setSpacing(5)
        self.subject_list_grid_layout.setObjectName("subject_list_grid_layout")
        self.subject_list_grid_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.scroll_area_vertical_layout.addWidget(self.subject_list_group_box)

        index = 0
        for subject in self.teacher_subjects:
            subject_label = QtWidgets.QLabel(subject, parent=self.subject_list_group_box)
            subject_label.setMinimumHeight(self.static["topic"]["height"])
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            subject_label.setFont(font)
            subject_label.setStyleSheet("background-color: #D9F2D0; border: 2px solid white; border-radius:10; padding-left:20px;padding-right:20px")
            subject_label.setObjectName(f"subject_label_{subject}")
            self.subject_list_grid_layout.addWidget(subject_label, index, 0, 1, 1)

            remove_subject_btn = QtWidgets.QPushButton("Eltávolítás", parent=self.subject_list_group_box)
            remove_subject_btn.setMinimumHeight(self.static["topic"]["height"])
            font = QtGui.QFont()
            font.setPointSize(self.static["font-sizes"]["text"])
            remove_subject_btn.setFont(font)
            remove_subject_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
            remove_subject_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
            remove_subject_btn.setObjectName(f"remove_subject_btn_{subject}")
            self.subject_list_grid_layout.addWidget(remove_subject_btn, index, 1, 1, 1)
            remove_subject_btn.clicked.connect(teacher_page.remove_subject)

            index+=1

    def subjects(self):
        self.subject_combo_box.clear()
        self.subject_combo_box.addItem("")
        self.subject_combo_box.setItemText(0, "")
        index = 1
        for subject in self.subject_data:
            if subject not in self.teacher_subjects:
                self.subject_combo_box.addItem("")
                self.subject_combo_box.setItemText(index, subject)
                index+=1
        
    def setupUi(self, teacher_page):
        teacher_page.setObjectName("teacher_page")
        teacher_page.resize(720, 480)
        teacher_page.setMinimumSize(QtCore.QSize(720, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 242, 208))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 203, 235))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        teacher_page.setPalette(palette)

        self.teacher_vertical_layout = QtWidgets.QVBoxLayout(teacher_page)
        self.teacher_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.teacher_vertical_layout.setSpacing(self.static["layout-spacing"])
        self.teacher_vertical_layout.setObjectName("teacher_vertical_layout")
        self.teacher_vertical_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.menu_group_box = QtWidgets.QGroupBox(parent=teacher_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.menu_group_box.sizePolicy().hasHeightForWidth())
        self.menu_group_box.setSizePolicy(sizePolicy)
        self.menu_group_box.setMinimumHeight(self.static["topic"]["height"])

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.menu_group_box.setPalette(palette)
        self.menu_group_box.setAutoFillBackground(True)
        self.menu_group_box.setStyleSheet("")
        self.menu_group_box.setTitle("")
        self.menu_group_box.setObjectName("menu_group_box")

        self.menu_horizontal_layout = QtWidgets.QHBoxLayout(self.menu_group_box)
        self.menu_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])
        self.menu_horizontal_layout.setSpacing(5)
        self.menu_horizontal_layout.setObjectName("menu_horizontal_layout")

        self.menu_label = QtWidgets.QLabel(parent=self.menu_group_box)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["title"])
        self.menu_label.setFont(font)
        self.menu_label.setObjectName("menu_label")
        self.menu_horizontal_layout.addWidget(self.menu_label)

        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.menu_horizontal_layout.addItem(spacerItem)

        self.font_size_combo_box = QtWidgets.QComboBox(parent=self.menu_group_box)
        self.font_size_combo_box.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["size-menu"])
        self.font_size_combo_box.setFont(font)
        self.font_size_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.font_size_combo_box.setStyleSheet("")
        self.font_size_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.font_size_combo_box.setObjectName("font_size_combo_box")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.font_size_combo_box.addItem("")
        self.menu_horizontal_layout.addWidget(self.font_size_combo_box)

        self.back_to_main_page_cmd_link_btn = QtWidgets.QCommandLinkButton(parent=self.menu_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.back_to_main_page_cmd_link_btn.sizePolicy().hasHeightForWidth())
        self.back_to_main_page_cmd_link_btn.setSizePolicy(sizePolicy)
        self.back_to_main_page_cmd_link_btn.setMinimumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        self.back_to_main_page_cmd_link_btn.setMaximumSize(QtCore.QSize(self.static["menu"]["backtrack-width-big"], 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(self.static["font-sizes"]["text"])
        self.back_to_main_page_cmd_link_btn.setFont(font)
        self.back_to_main_page_cmd_link_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_to_main_page_cmd_link_btn.setObjectName("back_to_main_page_cmd_link_btn")
        icon = QtGui.QIcon('utils/images/left-arrow.png')           
        self.back_to_main_page_cmd_link_btn.setIcon(icon)
        self.menu_horizontal_layout.addWidget(self.back_to_main_page_cmd_link_btn)
        self.teacher_vertical_layout.addWidget(self.menu_group_box)

        self.groupBox = QtWidgets.QGroupBox(parent=teacher_page)
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")

        self.save_horizontal_layout = QtWidgets.QHBoxLayout(self.groupBox)
        self.save_horizontal_layout.setContentsMargins(self.static["menu"]["layout"]["left"], self.static["menu"]["layout"]["top"], self.static["menu"]["layout"]["right"], self.static["menu"]["layout"]["bottom"])
        self.save_horizontal_layout.setSpacing(self.static["subtitle-spacing"])
        self.save_horizontal_layout.setObjectName("save_horizontal_layout")
        self.save_horizontal_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.save_btn = QtWidgets.QPushButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_btn.setFont(font)
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                    "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.save_btn.setObjectName("save_btn")
        self.save_horizontal_layout.addWidget(self.save_btn)

        self.save_and_new_btn = QtWidgets.QPushButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.save_and_new_btn.setSizePolicy(sizePolicy)
        self.save_and_new_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.save_and_new_btn.setFont(font)
        self.save_and_new_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_and_new_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                            "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.save_and_new_btn.setObjectName("save_and_new_btn")
        self.save_horizontal_layout.addWidget(self.save_and_new_btn)
        self.teacher_vertical_layout.addWidget(self.groupBox)

        if teacher_page.email=="" or teacher_page.teacher_name=="":
            self.save_btn.setEnabled(False)
            self.save_and_new_btn.setEnabled(False)
        else:
            self.save_and_new_btn.setHidden(True)

        self.title_group_box = QtWidgets.QGroupBox(parent=teacher_page)
        """sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.title_group_box.setSizePolicy(sizePolicy)"""
        self.title_group_box.setStyleSheet("border:none;")
        self.title_group_box.setTitle("")
        self.title_group_box.setObjectName("title_group_box")
        #self.title_group_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.teacher_vertical_layout.addWidget(self.title_group_box)

        self.title_grid_layout = QtWidgets.QGridLayout(self.title_group_box)
        self.title_grid_layout.setContentsMargins(0,0,0,0)
        self.title_grid_layout.setHorizontalSpacing(10)
        self.title_grid_layout.setVerticalSpacing(10)
        self.title_grid_layout.setObjectName("title_grid_layout")
        self.title_grid_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)        

        self.teacher_name_line_edit = QtWidgets.QLineEdit(teacher_page.teacher_name, parent=self.title_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHeightForWidth(self.teacher_name_line_edit.sizePolicy().hasHeightForWidth())
        self.teacher_name_line_edit.setSizePolicy(sizePolicy)
        self.teacher_name_line_edit.setMinimumHeight(self.static["topic"]["height"]-10)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.teacher_name_line_edit.setFont(font)
        self.teacher_name_line_edit.setObjectName("teacher_name_line_edit")
        self.teacher_name_line_edit.setValidator(NAME_VALIDATOR)
        self.teacher_name_line_edit.setMaxLength(255)
        self.teacher_name_line_edit.setPlaceholderText("Név")
        self.title_grid_layout.addWidget(self.teacher_name_line_edit, 0, 0, 1, 2)

        if teacher_page.email=="":
            self.teacher_email_line_edit = QtWidgets.QLineEdit(teacher_page.email, parent=self.title_group_box)
            self.teacher_email_line_edit.setValidator(EMAIL_VALIDATOR)
            self.teacher_email_line_edit.setMaxLength(255)
            self.teacher_email_line_edit.setPlaceholderText("E-mail")
        else:
            self.teacher_email_line_edit = QtWidgets.QLabel(teacher_page.email, parent=self.title_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHeightForWidth(self.teacher_email_line_edit.sizePolicy().hasHeightForWidth())
        self.teacher_email_line_edit.setSizePolicy(sizePolicy)
        self.teacher_email_line_edit.setMinimumHeight(self.static["topic"]["height"]-10)
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.teacher_email_line_edit.setFont(font)
        self.teacher_email_line_edit.setObjectName("teacher_email_line_edit")        
        self.title_grid_layout.addWidget(self.teacher_email_line_edit, 0, 2, 1, 2)

        self.subject_combo_box = QtWidgets.QComboBox(parent=self.title_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHeightForWidth(self.subject_combo_box.sizePolicy().hasHeightForWidth())
        self.subject_combo_box.setSizePolicy(sizePolicy)
        self.subject_combo_box.setMinimumSize(QtCore.QSize(self.static["topic"]["small-width"]-60, self.static["topic"]["height"]-10))
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.subject_combo_box.setFont(font)
        self.subject_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.subject_combo_box.setStyleSheet("QComboBox {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                    "QComboBox:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                                    "QAbstractItemView{selection-color: black; selection-background-color: #55aa00; background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;padding-top:5px; padding-bottom:5px;}")
        self.subject_combo_box.setObjectName("subject_combo_box")
        self.title_grid_layout.addWidget(self.subject_combo_box, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.add_subject_btn = QtWidgets.QPushButton(parent=self.title_group_box)
        self.add_subject_btn.setMinimumHeight(self.static["topic"]["height"])
        font = QtGui.QFont()
        font.setPointSize(self.static["font-sizes"]["text"])
        self.add_subject_btn.setFont(font)
        self.add_subject_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_subject_btn.setStyleSheet("QPushButton {background-color: #D9F2D0; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}\n"
                                            "QPushButton:hover {background-color: #55aa00; border: 2px solid black; border-radius:10; padding-left:20px;padding-right:20px;}")
        self.add_subject_btn.setObjectName("add_subject_btn")
        self.title_grid_layout.addWidget(self.add_subject_btn, 1, 1, 1, 3)
        self.add_subject_btn.clicked.connect(teacher_page.add_subject)
        self.add_subject_btn.setEnabled(False)
        
        self.scrollArea = QtWidgets.QScrollArea(parent=teacher_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("border:none; background-color:#83cbeb")
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)        

        self.scroll_area_vertical_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scroll_area_vertical_layout.setObjectName("scroll_area_vertical_layout")
        self.scroll_area_vertical_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.subject_list_group_box = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.subject_list_group_box.setTitle("")
        self.subject_list_group_box.setObjectName("subject_list_group_box")

        self.subject_list_grid_layout = QtWidgets.QGridLayout(self.subject_list_group_box)
        self.subject_list_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.subject_list_grid_layout.setSpacing(5)
        self.subject_list_grid_layout.setObjectName("subject_list_grid_layout")

        self.scroll_area_vertical_layout.addWidget(self.subject_list_group_box)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.teacher_vertical_layout.addWidget(self.scrollArea)

        self.retranslateUi(teacher_page)

        match teacher_page.user_settings['font-size']:
            case 'small':
                self.font_size_combo_box.setCurrentIndex(0)
            case 'medium':
                self.font_size_combo_box.setCurrentIndex(1)
            case 'big':
                self.font_size_combo_box.setCurrentIndex(2)

        QtCore.QMetaObject.connectSlotsByName(teacher_page)

    def retranslateUi(self, teacher_page):
        _translate = QtCore.QCoreApplication.translate
        teacher_page.setWindowTitle(_translate("teacher_page", "SmartStudy"))
        teacher_page.setWindowIcon(QtGui.QIcon("utils/images/window-icon.png"))
        self.menu_label.setText(_translate("teacher_page", "Tanár szerkesztése/Új"))
        self.font_size_combo_box.setItemText(0, _translate("teacher_page", "Kis betűméret"))
        self.font_size_combo_box.setItemText(1, _translate("teacher_page", "Közepes betűméret"))
        self.font_size_combo_box.setItemText(2, _translate("teacher_page", "Nagy betűméret"))
        self.back_to_main_page_cmd_link_btn.setText(_translate("teacher_page", "Vissza a kezdőlapra"))
        self.save_btn.setText(_translate("teacher_page", "Mentés"))
        self.save_and_new_btn.setText(_translate("teacher_page", "Mentés és Új"))
        self.add_subject_btn.setText(_translate("teacher_page", "Tantárgy hozzáadása a tanított tárgyakhoz"))
